# Generated by Django 6.0.6 on 2026-06-12 17:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('partner', models.CharField(blank=True, max_length=100, verbose_name='Партнёр')),
                ('icon', models.CharField(blank=True, max_length=20, verbose_name='Иконка (эмодзи)')),
                ('cost_points', models.PositiveIntegerField(verbose_name='Стоимость в GreenPoints')),
                ('stock', models.PositiveIntegerField(blank=True, null=True, verbose_name='Остаток (пусто = безлимит)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
            ],
            options={
                'verbose_name': 'Награда',
                'verbose_name_plural': 'Награды',
                'ordering': ['cost_points'],
            },
        ),
        migrations.AddField(
            model_name='childprofile',
            name='spent_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Потрачено баллов'),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='age',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(17)], verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='max_age',
            field=models.PositiveSmallIntegerField(default=10, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(17)], verbose_name='Максимальный возраст'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='min_age',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(17)], verbose_name='Минимальный возраст'),
        ),
        migrations.CreateModel(
            name='RewardRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_spent', models.PositiveIntegerField(verbose_name='Списано баллов')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код купона')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='green_app.childprofile', verbose_name='Ребёнок')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL, verbose_name='Родитель')),
                ('reward', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='redemptions', to='green_app.reward', verbose_name='Награда')),
            ],
            options={
                'verbose_name': 'Обмен награды',
                'verbose_name_plural': 'Обмены наград',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoiceDiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст записи')),
                ('word_count', models.PositiveIntegerField(default=0, verbose_name='Кол-во слов')),
                ('ai_feedback', models.TextField(blank=True, verbose_name='Отзыв AI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to='green_app.childprofile', verbose_name='Ребёнок')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diary_entries', to=settings.AUTH_USER_MODEL, verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Запись дневника',
                'verbose_name_plural': 'Записи дневника',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(verbose_name='Код сертификата')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('icon', models.CharField(blank=True, max_length=20, verbose_name='Иконка (эмодзи)')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Выдан')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='green_app.childprofile', verbose_name='Ребёнок')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-issued_at'],
                'unique_together': {('child', 'code')},
            },
        ),
    ]
