# Generated by Django 6.0.6 on 2026-06-15 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('green_app', '0003_seed_rewards'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='connection_code',
            field=models.CharField(blank=True, db_index=True, max_length=6, null=True, unique=True, verbose_name='Код подключения'),
        ),
        migrations.AddField(
            model_name='childprofile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_profile', to=settings.AUTH_USER_MODEL, verbose_name='Аккаунт ребёнка'),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to=settings.AUTH_USER_MODEL, verbose_name='Родитель (владелец)'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('parent', 'Родитель'), ('child', 'Ребёнок'), ('admin', 'Администратор')], default='parent', max_length=10, verbose_name='Роль'),
        ),
        migrations.CreateModel(
            name='ParentInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_email', models.EmailField(max_length=254, verbose_name='Email родителя')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Принято')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='green_app.childprofile', verbose_name='Ребёнок')),
            ],
            options={
                'verbose_name': 'Приглашение родителю',
                'verbose_name_plural': 'Приглашения родителям',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Подключён')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='green_app.childprofile', verbose_name='Ребёнок')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to=settings.AUTH_USER_MODEL, verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Связь родитель-ребёнок',
                'verbose_name_plural': 'Связи родитель-ребёнок',
                'ordering': ['-created_at'],
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
